<?php
$title = 'Contactos';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    <button class="btn" data-toggle="collapse" data-target="#Form" style="color:#5252e0"><span class='glyphicon glyphicon-plus' aria-hidden="true"></span>Agregar nuevo contacto</button>
    <?php if (isset($resp)){
    	echo($resp);
    	} ?>
	<div id="Form" class="collapse">
		<?php
			$form = $this->form;

			$form->prepare();

			$form->setAttributes(array(
			    'action' => $this->url($this->module, array('action' => $this->action)),
			    'metod'  => 'POST'));

			$formLabel = $this->plugin('formLabel', array('class' => 'sr-only'));

			echo $this->form()->openTag($form);

			foreach ($form as $key => $value) {
			    echo '<div class="form-group">';
			    $element = $form->get($key);
			    try {
			        echo $this->formLabel($element);
			    } catch (Exception $e) {

			    }
			    if ($key === 'idContacto') {
			        $element->setAttributes(['value' => $newId]);
			    }
			    echo $this->formElement($element);
			    echo $this->formElementErrors($element);
			    echo '</div>';
			}

			echo $this->form()->closeTag($form);
		?>
	</div>
</p>
<table class="table table-hover">
<tr>
    <th>idContacto</th>
    <th>Nombre</th>
    <th>Telefono</th>
    <th>e-mail</th>
    <th>Categoria</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($data as $item): ?>
    <tr>
        <td><?=$this->escapeHtml($item->idContacto)?></td>
        <td><?=$this->escapeHtml($item->nombre)?></td>
        <td><?=$this->escapeHtml($item->telefono)?></td>
        <td><?=$this->escapeHtml($item->correo)?></td>
        <td><?=$this->escapeHtml($item->nombreCategoria)?></td>
        <td>
            <a href="<?=$this->url('contacto', ['action' => 'edit', 'id' => $item->idContacto])?>" style='color: green'><span class='glyphicon glyphicon-pencil' aria-hidden="true"></span></a>
            <a href="<?=$this->url('contacto', ['action' => 'delete', 'id' => $item->idContacto])?>" style='color: red'><span class='glyphicon glyphicon-remove' aria-hidden="true"></span></a>
        </td>
    </tr>
<?php endforeach;?>
</table>